[_]
schema-version = "0.2"
id = "dev.veith.uuids"
name = "UUIDs Generator"

[io.buildpacks]
builder = "paketobuildpacks/builder-jammy-full"

[[io.buildpacks.group]]
id = "paketo-buildpacks/nodejs"
version = "7.1.0"

[[io.buildpacks.build.env]]
name = "BP_NODE_VERSION"
value = "22.12.0"

[[io.buildpacks.build.env]]
name = "NODE_ENV"
value = "production"

[[io.buildpacks.build.env]]
name = "SKIP_ENV_VALIDATION"
value = "1"
